### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by haipronl** [yilinyang1/NN-ensemble-relaxer#5]
Hello,

I used the script "python libsymf_builder.py". However, I got this problem.

generating ./_libsymf.cpp
(already up-to-date)
the current directory is '/home/users/hai/soft/NN_ensemble_relaxer/utils'
calculate_sf.cpp: In function ‘int calculate_sf(double**, double**, double**, int*, int, int*, int, int**, double**, int, double**, double**)’:
calculate_sf.cpp:36:25: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
         for (int i=0; i < sizeof(IMPLEMENTED_TYPE) / sizeof(IMPLEMENTED_TYPE[0]); i++) {
                       ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Could you please take a look at it?

Thank you.

**Comment by yilinyang1** [comment]
Hi, this is a warning and should not affect the actual building. Also, I've update the code to solve this warning. You can try it again. Thanks!
